version: "3.3"

networks:
   default:
      external:
         name: syntheticnet

services:
  synthetic-data-generator-file:
    container_name: csv-data-sender
    build:
      context: .
    environment:
      - SOCK_LISTENER_HOST=publisher
      - SOCK_LISTENER_PORT=8053